In [ ]:
# Scalar 0D
s = 66
s

66

In [ ]:
# Vector 1D
# Row Vector and Column Vector
import numpy as np
x = np.array([1, 2, 3])
print(x)
print(x.reshape((3, 1)))


[1 2 3]
[[1]
 [2]
 [3]]


In [ ]:
# Matrices 2D Arrays
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(np.arange(12).reshape((3, 4)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Tensors are 3D or more 
t = np.arange(36).reshape((3, 3, 4))
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [ ]:
print(t[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(t[0, 1])

[4 5 6 7]


In [ ]:
print(t[0, 1, 2])

6


In [ ]:
# We can define 5 Order Tensor like this
w = np.zeros((9, 9, 9, 9, 9))
w[4, 1, 2, 0, 1]

0.0

In [ ]:
# We can treat scalar as high order tensor
t = np.array(42).reshape((1, 1, 1, 1, 1))
print(t)
print(t.shape)
t[0, 0, 0, 0, 0]

[[[[[42]]]]]
(1, 1, 1, 1, 1)


42

In [ ]:
# Adding 1 as dimension at first
t = np.array([[1, 2, 3], [4, 5, 6]])
print(t)

w = t[np.newaxis, :, :]
print(w.shape)
print(w)

[[1 2 3]
 [4 5 6]]
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [ ]:
# Arithematic with Tensors
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([10, 100, 1000])
d = np.array([10, 11])

print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[  10  100 1000]
[10 11]


In [ ]:
# Arithematic operations are done element wise
print(a+b)
print('\n')
print(a-b)
print('\n')
print(a*b)
print('\n')
print(a/b)

[[ 8 10 12]
 [14 16 18]]


[[-6 -6 -6]
 [-6 -6 -6]]


[[ 7 16 27]
 [40 55 72]]


[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
# Broadcasting c to a
print(a+c)
print('\n')
print(c*a)
print('\n')
print(a/c)

[[  11  102 1003]
 [  14  105 1006]]


[[  10  200 3000]
 [  40  500 6000]]


[[0.1   0.02  0.003]
 [0.4   0.05  0.006]]


In [ ]:
# d cannot be broadcasted because its last dimension is diferent
print(a+d)

ValueError: ignored

In [ ]:
d = d.reshape((2, 1))
print(d)

[[10]
 [11]]


In [ ]:
print(d.shape)

(2, 1)


In [ ]:
print(a+d)

[[11 12 13]
 [15 16 17]]


In [1]:
import numpy as np

In [2]:
# Unit vector is vector divided by the magnitude
# Pythogorus theorm c**2 = a**2 + b**2
v = np.array((2, -4, 3))
u = v / np.sqrt((v*v).sum())
print(u)

[ 0.37139068 -0.74278135  0.55708601]


In [3]:
# vector transpose in numpy
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [4]:
print(v.reshape((3, 1)))
print(v.reshape((1, 3)))

[[1]
 [2]
 [3]]
[[1 2 3]]


In [5]:
# simple array cannot transpose
print(v.transpose())
print(v.T)

[1 2 3]
[1 2 3]


In [6]:
# you have to make v as vector first
v = v.reshape((1, 3))
print(v)

[[1 2 3]]


In [7]:
print(v.transpose())
print(v.T)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [8]:
# dot product/inner product function
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

def inner(a, b):
  s = 0.0
  for i in range(len(a)):
    s = s + a[i] * b[i]
  return s

inner(a, b)

70.0

In [9]:
# but with numpym, you can do it much easier
(a*b).sum()

70

In [10]:
# also
np.dot(a,b)

70

In [12]:
# dot product is alos a.b = cos(angle) ||a|| ||b||
# so angle = cos to the power -1  (a.b/||a|| ||b||)
A = np.sqrt(np.dot(a, a))
B = np.sqrt(np.dot(b, b))
t = np.arccos(np.dot(a, b)/(A*B))
# Converting radians into angles
t * (180/np.pi)

14.335170291600924

In [13]:
# in 3D space, othognol vectors dot product is 0
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
np.dot(a, b)


0

In [15]:
# taking angle 0 dot product is 90 degrees
t = np.arccos(0)
print(t*(180/np.pi))

90.0


In [16]:
# The projection of one vector onto another calculates the amount of the fist vector that's in the direction of the second.
# The projection of a onto b is 
# projb a = (a.b/(||b||**2))*b
a = np.array([1, 1])
b = np.array([1, 0])
p = (np.dot(a, b)/np.dot(b, b)) * b
print(p)

[1. 0.]


In [17]:
c = np.array([-1, 1])
p = (np.dot(c, b)/np.dot(b, b))*b
print(p)

[-1. -0.]


In [18]:
# Outer product is multiplying each component of a with b
# It returns a matrix
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.dot(a, b)

70

In [19]:
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [20]:
# Cross product
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(np.cross(a, b))

[0 0 1]


In [21]:
c = np.array([1, 1, 0])
print(np.cross(a, c))

[0 0 1]


In [22]:
# Matrix Multiplication
def matrixmul(A, B):
  I, K = A.shape
  J = B.shape[1]
  C = np.zeros((I, J), dtype=A.dtype)
  for i in range(I):
    for j in range(J):
      for k in range(K):
        C[i, j] = C[i, j] + (A[i, k] * B[k, j])

  return C

In [23]:
av = np.array([1, 2, 3])
ar = np.array([[1, 2, 3]])
ac = np.array([[1], [2], [3]])
av.shape

(3,)

In [24]:
ar.shape

(1, 3)

In [25]:
ac.shape

(3, 1)

In [26]:
a1 = np.array([1, 2, 3])
ar = np.array([[1, 2, 3]])
ac = np.array([[1], [2], [3]])
b1 = np.array([1, 2, 3])
br = np.array([[1, 2, 3]])
bc = np.array([[1], [2], [3]])
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [27]:
# dot function to evaluate matrices multiplication
def dot(a, b):
  try:
    return np.dot(a, b)
  except:
    return "fails"

In [28]:
# a1, b1 result 14 (scalar)
dot(a1, b1)

14

In [29]:
# a1, br (fails)
dot(a1, br)

'fails'

In [30]:
# a1, bc [14] (1 Vector)
dot(a1, bc)

array([14])

In [31]:
# ar, b1 [14] (1 Vector)
dot(ar, b1)

array([14])

In [32]:
# ac, b1 (fails)
dot(ac, b1)

'fails'

In [33]:
# ac, br outerproduct
dot(ac, br)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [34]:
# ac, bc (fails)
dot(ac, bc)

'fails'

In [35]:
# A, a1 [14, 32, 50] (3 Vector)
dot(A, a1)

array([14, 32, 50])

In [36]:
# A, ar (fails)
dot(A, ar)

'fails'

In [37]:
# A, ac column vector [14, 32, 50]
dot(A, ac)

array([[14],
       [32],
       [50]])

In [38]:
# a1, A [30, 36, 42] (3 Vector)
dot(a1, A)

array([30, 36, 42])

In [39]:
# ar, A [30, 36, 42] (1 x 3 matrix)
dot(ar, A)

array([[30, 36, 42]])

In [40]:
# ac, A (fails)
dot(ac, A)

'fails'

In [41]:
# A, B Matrix
dot(A, B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])