# Newton 1 Dimension

In [ ]:
import numpy as np

In [ ]:
def f(x):
  return 2.0 - x * x

In [ ]:
def d(x):
  return -2.0 * x

In [ ]:
x = 1.0

In [ ]:
for i in range(5):
  x = x - f(x)/d(x)
  print("%2d: %0.16f" % (i+1,x))

 1: 1.5000000000000000
 2: 1.4166666666666667
 3: 1.4142156862745099
 4: 1.4142135623746899
 5: 1.4142135623730951


In [ ]:
print()
print("NumPy says sqrt(2) = %0.16f for a deviation of %0.16f" % (np.sqrt(2), np.abs(np.sqrt(2)-x)))
print()


NumPy says sqrt(2) = 1.4142135623730951 for a deviation of 0.0000000000000000



# Newton 2 Dimension and Inverse of Jacobian Matrix

##**$A =  \begin{pmatrix}
  a & b
  \\
  c & d
 \end{pmatrix}$**

##**$A^{-1} = \frac{1}{det(A)} \begin{pmatrix}
  d & -b
  \\
  -c & a
 \end{pmatrix}$**

In [ ]:
import numpy as np

def f(x):
  x0, x1 = x[0, 0], x[1, 0]
  return np.array([[4*x0 - 2*x0*x1], [2*x1 + x0*x1 - 2*x1**2]])

In [ ]:
def JI(x):
  x0, x1 = x[0, 0], x[1, 0]
  d = (4 - 2*x1) * (2 + x0 - 4*x1) + 2*x0*x1
  return (1/d) * np.array([[2 + x0 - 4*x1, 2*x0], [-x1, 4 - 2*x0]])

In [ ]:
x0 = float(input("x0: "))



x0: 1.6


In [ ]:
x1 = float(input("x1: "))

x1: 1.8


In [ ]:
x = np.array([[x0], [x1]])

In [ ]:
N = 20
for i in range(N):
  x = x - JI(x) @ f(x)
  if (i > (N-10)):
    print("%4d: (%0.8f, %0.8f)" % (i, x[0, 0], x[1, 0]))

  11: (2.00000000, 2.00000000)
  12: (2.00000000, 2.00000000)
  13: (2.00000000, 2.00000000)
  14: (2.00000000, 2.00000000)
  15: (2.00000000, 2.00000000)
  16: (2.00000000, 2.00000000)
  17: (2.00000000, 2.00000000)
  18: (2.00000000, 2.00000000)
  19: (2.00000000, 2.00000000)


In [ ]:
print(x)

[[2.]
 [2.]]


# EigenValues of Jacobian

In [ ]:
import numpy as np

In [ ]:
np.linalg.eig([[4, 0], [0, 2]])[0]

array([4., 2.])

In [ ]:
np.linalg.eig([[2, 0], [1, -2]])[0]

array([-2.,  2.])

In [ ]:
np.linalg.eig([[0, -4], [2, -4]])[0]

array([-2.+2.j, -2.-2.j])