## Scalars, Vectors, Metrices and Tensors

### Scalar

In [ ]:
s = 66
s

66

### Vectors

In [ ]:
# Row Vector
import numpy as np
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [ ]:
# Column Vector
print(x.reshape(3, 1))

[[1]
 [2]
 [3]]


### Matrices

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
A.shape

(3, 3)

In [ ]:
print(np.arange(12).reshape((3, 4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Tensors

In [ ]:
t = np.arange(36).reshape((3, 3, 4))
print(t)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [ ]:
print(t[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(t[0, 1])

[4 5 6 7]


In [ ]:
print(t[0, 1, 2])

6


In [ ]:
w = np.zeros((9, 9, 9, 9, 9))
print(w[4, 1, 2, 0, 1])

0.0


In [ ]:
# Adding dimension to a tensor
t = np.array(42)

In [ ]:
print(t)

42


In [ ]:
t = t.reshape((1, 1, 1, 1, 1))

In [ ]:
print(t)

[[[[[42]]]]]


In [ ]:
t.shape

(1, 1, 1, 1, 1)

In [ ]:
t[0, 0, 0, 0, 0]

42

In [ ]:
t = np.array([[1, 2, 3], [4, 5, 6]])
print(t)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Numpy way of adding dimension
w = t[np.newaxis, :, :]
w.shape

(1, 2, 3)

In [ ]:
print(w)

[[[1 2 3]
  [4 5 6]]]


## Arthmetic and Tensor

### Array Operations

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([10, 100, 1000])
d = np.array([10, 11])

In [ ]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b)

[[ 7  8  9]
 [10 11 12]]


In [ ]:
print(c)

[  10  100 1000]


In [ ]:
print(d)

[10 11]


Element wise operations

In [ ]:
print(a+b)

[[ 8 10 12]
 [14 16 18]]


In [ ]:
print(a-b)

[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [ ]:
print(a/b)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
print(b**a)

[[      7      64     729]
 [  10000  161051 2985984]]


Broadcasting

In [ ]:
print(a+c)

[[  11  102 1003]
 [  14  105 1006]]


In [ ]:
print(c*a)

[[  10  200 3000]
 [  40  500 6000]]


In [ ]:
print(a/c)

[[0.1   0.02  0.003]
 [0.4   0.05  0.006]]


In [ ]:
print(a+d)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
# if we reshape d so that it's a 2D array with shape 2 x 1
d.shape

(2,)

In [ ]:
d = d.reshape((2, 1))
d.shape

(2, 1)

In [ ]:
print(d)

[[10]
 [11]]


In [ ]:
print(a+d)

[[11 12 13]
 [15 16 17]]


## Vector Operations

### Unit Vector

#${v} = \frac {v}{||v||}$

In [ ]:
import numpy as np

In [ ]:
# Converting vector into its unit vector; i.e, the magnitude of one
v = np.array((2, -4, 3))
u = v / np.sqrt((v*v).sum())
print(u)

[ 0.37139068 -0.74278135  0.55708601]


### Transpose

In [ ]:
# Three ways in numpy to transpose
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [ ]:
print(v.reshape((3, 1)))

[[1]
 [2]
 [3]]


In [ ]:
print(v.reshape((1, 3)))

[[1 2 3]]


In [ ]:
print(v)

[1 2 3]


In [ ]:
print(v.transpose())

[1 2 3]


In [ ]:
print(v.T)

[1 2 3]


In [ ]:
v = v.reshape((1, 3))
print(v)

[[1 2 3]]


In [ ]:
print(v.transpose())

[[1]
 [2]
 [3]]


In [ ]:
print(v.T)

[[1]
 [2]
 [3]]


In [ ]:
v.shape

(1, 3)

In [ ]:
print(v)

[[1 2 3]]


In [ ]:
v1 = v.T
v1.shape

(3, 1)

### Dot Product

# \begin{align}
\mathbf{a} \cdot \mathbf{b} = (a,b) = {a^Tb} =
&= \sum_{k=0}^{n-1} a_K b_k \end{align}

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
def inner(a, b):
  s = 0.0
  for i in range(len(a)):
    s += a[i]*b[i]
  return s

In [ ]:
inner(a, b)

70.0

In [ ]:
(a*b).sum()

70

In [ ]:
np.dot(a,b)

70


#$θ = cos^-1 \frac{\mathbf{a} \cdot \mathbf{b}}{||a|| ||b||}$

In [ ]:
A = np.sqrt(np.dot(a, a))
B = np.sqrt(np.dot(b, b))
t = np.arccos(np.dot(a, b)/(A*B))
# Turning radians into degrees
t*(180/np.pi)

14.335170291600924

In [ ]:
# Orthogonal[Perpendicular] Vectors in 3D
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
np.dot(a, b)

0

In [ ]:
t = np.arccos(0)
t * (180/np.pi)

90.0

### Projection

**$Proj_a b = \frac{\mathbf{a} \cdot \mathbf{b}}{||b||^2} b $**

In [ ]:
# a is in 45 degrees.
a = np.array([1, 1])
b = np.array([1, 0])
p = (np.dot(a, b)/np.dot(b,b))*b
print(p)

[1. 0.]


In [ ]:
c = np.array([-1, 1])
p = (np.dot(c,b)/np.dot(b,b))*b
print(p)

[-1. -0.]


### Outer Product

$a \oplus b = {ab^T} =  \begin{pmatrix}a_0b_0, a_0b_1, ......, a_0b_{n-1} \\
a_{m-1}b_0, a_{m-1}b_1, ......, a_{m-1}b_{n-1} \end{pmatrix}$

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [ ]:
np.dot(a, b)

70

In [ ]:
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

### Cross Product

**$ ab = ||a||||b||sin(\theta)\bar{n} $**





In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(np.cross(a, b))

[0 0 1]


In [ ]:
c = np.array([1, 1, 0])
print(np.cross(a, c))

[0 0 1]


## Matrix Operations

### Matrix Multiplication

In [ ]:
def matrixmul(A, B):
  I, K = A.shape
  J = B.shape[1]
  C = np.zeros((I, J), dtype=A.dtype)
  for i in range(I):
    for j in range(J):
      for k in range(K):
        C[i, j] = A[i, k] * B[k, j]
  return C

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
N = 100000

In [ ]:
print(A.shape)

(4, 3)


In [ ]:
print(B.shape)

(3, 2)


In [ ]:
print(A[1, :])

[4 5 6]


In [ ]:
print(B[:, 0])

[1 3 5]


In [ ]:
print(B.shape[1])

2


In [ ]:
print(B[1, :])

[3 4]


In [ ]:
print(A[0, 0])

1


In [ ]:
import time

In [ ]:
s = time.time()
for i in range(N):
  C = matrixmul(A, B)
e = time.time()
print("matrixmul: %0.6f" % (e-s,))

matrixmul: 1.877131


In [ ]:
print(C)

[[15 18]
 [30 36]
 [45 54]
 [60 72]]


In [ ]:
s = time.time()
for i in range(N):
  C = np.matmul(A, B)
e = time.time()
print("np.matmul: %0.6f" % (e-s,))

np.matmul: 0.146502


In [ ]:
C

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136]])

## Matrix Multiplication with Numpy

In [ ]:
import numpy as np

In [ ]:
av = np.array([1, 2, 3])
ar = np.array([[1, 2, 3]])
ac = np.array([[1], [2], [3]])

In [ ]:
av.shape

(3,)

In [ ]:
ar.shape

(1, 3)

In [ ]:
print(ar)

[[1 2 3]]


In [ ]:
ac.shape

(3, 1)

In [ ]:
print(ac)

[[1]
 [2]
 [3]]


In [ ]:
av.transpose()

array([1, 2, 3])

In [ ]:
ac.transpose()

array([[1, 2, 3]])

In [ ]:
ar

array([[1, 2, 3]])

In [ ]:
a1 = np.array([1, 2, 3])
ar = np.array([[1, 2, 3]])
ac = np.array([[1], [2], [3]])
b1 = np.array([1, 2, 3])
br = np.array([[1, 2, 3]])
bc = np.array([[1], [2], [3]])
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

### Numpy Dot Product

In [ ]:
import numpy as np

In [ ]:
def dot(a, b):
  try:
    return np.dot(a, b)
  except:
    return "fails"

In [ ]:
print()
print("np.dot examples:")
print("dot(a1, b1):"); print(dot(a1, b1))


np.dot examples:
dot(a1, b1):
14


In [ ]:
print("dot(a1, br):"); print(dot(a1, br))

dot(a1, br):
fails


In [ ]:
print("dot(a1, bc):"); print(dot(a1, bc))

dot(a1, bc):
[14]


In [ ]:
print("dot(a1, bc):"); print(dot(a1, bc))

dot(a1, bc):
[14]


In [ ]:
print("dot(ar, b1):"); print(dot(ar, b1))

dot(ar, b1):
[14]


In [ ]:
print("dot(ar, br):"); print(dot(ar, br))

dot(ar, br):
fails


In [ ]:
print("dot(ar, bc):"); print(dot(ar, bc))

dot(ar, bc):
[[14]]


In [ ]:
dot_rc = dot(ar, bc)
dot_rc.shape

(1, 1)

In [ ]:
print("dot(ac, bc):"); print(dot(ac, bc))

dot(ac, bc):
fails


In [ ]:
print("dot(ac, b1):"); print(dot(ac, b1))

dot(ac, b1):
fails


In [ ]:
# Outer Product
print("dot(ac, br):"); print(dot(ac, br))

dot(ac, br):
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
print("dot(ac, bc):"); print(dot(ac, bc))

dot(ac, bc):
fails


In [ ]:
A.shape

(3, 3)

In [ ]:
print("dot(A, a1):"); print(dot(A, a1))

dot(A, a1):
[14 32 50]


In [ ]:
print("dot(A, ar):"); print(dot(A, ar))

dot(A, ar):
fails


In [ ]:
print("dot(A, ac):"); print(dot(A, ac))

dot(A, ac):
[[14]
 [32]
 [50]]


In [ ]:
print("dot(a1, A):"); print(dot(a1, A))

dot(a1, A):
[30 36 42]


In [ ]:
print(a1.shape, A.shape)

(3,) (3, 3)


In [ ]:
print("dot(ar, A):"); print(dot(ar, A))

dot(ar, A):
[[30 36 42]]


In [ ]:
print("dot(ac,A):"); print(dot(ac,A))

dot(ac,A):
fails


In [ ]:
print("dot(A,B):"); print(dot(A,B))

dot(A,B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
print(np.outer(A, B.transpose()))

[[ 9  6  3  8  5  2  7  4  1]
 [18 12  6 16 10  4 14  8  2]
 [27 18  9 24 15  6 21 12  3]
 [36 24 12 32 20  8 28 16  4]
 [45 30 15 40 25 10 35 20  5]
 [54 36 18 48 30 12 42 24  6]
 [63 42 21 56 35 14 49 28  7]
 [72 48 24 64 40 16 56 32  8]
 [81 54 27 72 45 18 63 36  9]]


In [ ]:
print(np.outer(ac, br))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
